version: 0.2

env:
  variables:
    DESTROY: "true"   # true = destroy, false = apply

phases:
  install:
    commands:
      - echo "Installing Terraform"
      - yum install -y yum-utils
      - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - yum install -y terraform

  pre_build:
    commands:
      - echo "Entering terraform directory"
      - cd terraform
      - terraform version
      - terraform init

  build:
    commands:
      - echo "DESTROY flag is $DESTROY"
      - |
        if [ "$DESTROY" = "true" ]; then
          echo "Destroying infrastructure"
          terraform destroy -auto-approve
        else
          echo "Applying infrastructure"
          terraform apply -auto-approve
        fi
